/**
* Texts WS
* This WS was created for getting translations and templates
*
* OpenAPI spec version: 1.0
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


package co.nextwireless.texts.ui.client.swagger.model

import scala.Int
//import co.nextwireless.common.types._ - use impl per project
import co.nextwireless.texts.ws.server.swagger.zapi.impl._
import enumeratum._

            
sealed trait Language extends EnumEntry{
override def toString: String = this.getClass.getSimpleName.replace("$", "")
}
object Language extends Enum[Language] with CirceEnum[Language] {
val values = findValues
  case object en extends Language
  case object fr extends Language
  case object de extends Language
  case object it extends Language
  case object es extends Language

}


