/**
* Texts WS
* This WS was created for getting translations and templates
*
* OpenAPI spec version: 1.0
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


package co.nextwireless.texts.ui.client.swagger.model

//import co.nextwireless.common.types._ - use impl per project
import co.nextwireless.texts.ui.client.swagger.zapi.impl._
//import enumeratum._

    case class Page (
        page_id: PageId,
        text_ids: List[String]
    )

    object Page {
    }


